name: NuclearGoogleAnalytics
main:  com.haniokasai.nukkit.GoogleAnalytics.GoogleAnalyticsPlugin
version: 1.0.0
author: haniokasai
api: ["1.0.0"]
description: GoogleAnalytics for nukkit
website: http://haniokasai.com
permissions:
     googleanalyticsplugin.ignore:
         description: Ignores all actions of this player
         default: false
